version: "3"

networks:
  net:
    external: false

services:
  server:
    build: ./gitea
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - net
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
 
  db:
    build: ./mysql
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - net
    volumes:
      - ./mysql:/var/lib/mysql

  jenkins:
    build: ./jenkins
    container_name: jenkins
    networks:
      - net
    user: root
    ports:
      - 8080:8080
    volumes:
      - ./jenkins:/var/jenkins_home
